hw_01: add fibo: func, tests and bin
gitalek/golang_think pull request #1
Opened 2020-10-14 10:01 UTC by gitalek

2020-10-14 10:56 UTC, DmitriyVTitov requested changes
Хорошо, но:
1. Каждый пакет должен быть в своём каталоге.
2. Пишите идиоматичные тесты. Без внешних зависимостей.

2020-10-14 10:56 UTC, DmitriyVTitov commented on hw_01/fibo/cmd/main.go
> +	fibo "golang_think/hw_01/fibo/pkg"
каждый пакет должен быть в своём каталоге, 'pkg' - каталог верхнего уровня, пакета не содержит

2020-10-14 10:56 UTC, DmitriyVTitov commented on hw_01/fibo/pkg/fibo_test.go
> +	a "github.com/stretchr/testify/assert"
я категорически против таких зависимостей.
причины:
1. я их знать не обязан и для проверки каждого задания изучить просто не могу
2. все эти "фреймворки" не решают никаких проблем, с тестированием в Go и так всё прекрасно
3. я не только не могу, но и не хочу это изучать
4. я не могу просто скопировать тест и быстро у себя запустить (а студентов - 35 человек).

2020-10-14 10:56 UTC, DmitriyVTitov commented on hw_01/fibo/pkg/fibo_test.go
> +		"0-th":  {num: 0, expected: 0},
крайне рекомендуется писать структуры с именами полей

2020-10-14 10:56 UTC, DmitriyVTitov commented on hw_01/fibo/pkg/fibo_test.go
> +	}
корректный тест:
```
	for name, testCase := range cases {
		t.Run(name, func(t *testing.T) {
			got := Fibo(testCase.num)
			want := testCase.expected
			if got != want {
				t.Fatalf("получили %d, ожидалось %d", got, want)
			}
		})
	}
```

неужели хуже, чем с assert?

2020-10-14 13:05 UTC, gitalek commented on hw_01/fibo/pkg/fibo_test.go
> +		"0-th":  {num: 0, expected: 0},
fixed

2020-10-14 13:05 UTC, gitalek commented on hw_01/fibo/pkg/fibo_test.go
> +	}
fixed

2020-10-14 13:06 UTC, gitalek commented on hw_01/fibo/pkg/fibo_test.go
> +	a "github.com/stretchr/testify/assert"
1-3 ok, юзаем стандартный пакет testing

2020-10-14 13:11 UTC, gitalek commented on hw_01/fibo/cmd/main.go
> +	fibo "golang_think/hw_01/fibo/pkg"
done

2020-10-14 18:43 UTC, DmitriyVTitov approved these changes
1. Рекомендую писать тесты идиоматично. Пример был в прошлой рецензии. Впрочем, занятие по тестированию ещё впереди.
2. Не выполнено требование к программе. На данном этапе не критично, но всё же.

2020-10-14 18:43 UTC, DmitriyVTitov commented on hw_01/fibo/pkg/fibo/fibo_test.go
> +	}
принято в тестах использовать переменные `got` и `want`
в сообщении о проваленном тесте, принято сначала писать что получили, потом что ожидалось.
я вам привёл канонический пример теста в рецензии.
конечно, ваше право писать всё по-своему, но стоит ли?

2020-10-14 18:43 UTC, DmitriyVTitov commented on hw_01/fibo/cmd/fibo/main.go
> +	res := fibo.Fibo(*n)
было ещё требование, что n <= 20.
как раз на случай рекурсивной реализации
для n около 40 вы не дождётесь результата (или 50, не помню)

2020-10-14 18:45 UTC, DmitriyVTitov commented on hw_01/fibo/pkg/fibo/fibo.go
> +func Fibo(n int) int {
Забыл:
`fibo.Fibo()` - не очень хорошо
`fibo.Num()` - очень хорошо

2020-10-15 05:42 UTC, gitalek commented on hw_01/fibo/cmd/fibo/main.go
> +	res := fibo.Fibo(*n)
done

2020-10-15 05:42 UTC, gitalek commented on hw_01/fibo/pkg/fibo/fibo.go
> +func Fibo(n int) int {
done

2020-10-15 05:42 UTC, gitalek commented on hw_01/fibo/pkg/fibo/fibo_test.go
> +	}
done

2020-11-24 03:37 UTC, merged